openapi: 3.0.0
info:
  title: Catalog API
  version: 1.0.0
paths:
  /products/:
    get:
      summary: Obtener todos los productos
      responses:
        '200':
          description: Lista de productos
    post:
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado exitosamente
  /products/{product_id}:
    get:
      summary: Obtener un producto por ID
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalles del producto
        '404':
          description: Producto no encontrado
    put:
      summary: Actualizar un producto
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado exitosamente
    delete:
      summary: Eliminar un producto
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Producto eliminado exitosamente
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        available:
          type: boolean
